### ISSUE TITLE
Support standard CACHE_TTL parameter

### ISSUE THREAD

**Issue by 9607835** [prerender/prerender-aws-s3-cache#4]
I was surprised to learn today that my prerender instance has probably never expired any s3 entries on its own.  I assumed this was a replacement for the previous version of prerenders s3 capabilities where I only needed to set `process.env.CACHE_TTL = [ttl]`.  Today I start noticing some SERIOUSLY outdated pages so after debuging everything else I check the code for this plugin and indeed there is no check of any kind for the age of the cached entry.  Two seconds or two decades, they are both the same to this plugin!

**Comment by thoop** [comment]
Yes the CACHE_TTL is not used in this repo and I think the proper way to expire S3 objects would be to use a lifecycle configuration on the actual S3 bucket to expire objects after a certain amount of time has passed.

So I think the best thing to do there is set your S3 bucket lifecycle configuration instead of modifying this plugin. If `s3.putObject` supports setting a TTL then I'd be happy to add it here but I didn't see anything about that when looking through the documentation.

**Comment by vesper8** [comment]
@thoop I think this answer here explains how to set cache expiry when using `putObject` https://stackoverflow.com/a/19415431/1419775

It would be great if this could be built in to this plugin
